### ISSUE TITLE
Nodes als PopUp öffnen in einem Artikel

### ISSUE THREAD

**Issue by m-werk** [postyou/contao-easy-popup#3]
Hallo,

wenn ich einen Link für das PopUp mache, wird es auch als solches angezeigt, wenn ich auf den Link klicke.

Erstelle ich aber ein Element mit dem Nodes, dann wird dieser fix in dem Artikel eingebunden und nicht als klassisches Popup dargestellt. Es fehlt auch hier der Button zum schließen, da es ja kein Link ist.

Gibt es eine Möglichkeit, so dass dieser Nodes auch als PopUp dargestellt werden kann, wenn er als Element in einem Artikel sich befindet?

LG, Andi

**Comment by MarkejN** [comment]
Derzeit läuft alles über den Insert-Tag `popup_url`. Die Anzeige des Popups ohne diesen Link funktioniert noch nicht. Was wäre dein Anwendungsfall dafür? Möchtest du verhindern, dass das Popup am Seitenende eingefügt wird?

Du könntest es aber wahrscheinlich jetzt schon umsetzen, indem du das Template `node_default.html5` anpasst und ähnlich dem `popup.html.twig` aufbaust. Das angepasste Template kannst du bei dem jeweiligen Node-Artikel auswählen, wenn du die Checkbox "Wrapper hinzufügen" aktivierst.

**Comment by m-werk** [comment]
Hallo, ich möchte das Popup automatisch am Seitenanfang einbauen. Wenn jemand die Seite besucht, soll sich gleich das Popup öffnen.
Wie kann ich das twig-Template auf html5 umbauen, so dass ich es als Wrapper verwenden kann? Dort wird kein twig erkannt.

**Comment by MarkejN** [comment]
So könnte man es z.B. umsetzen:

Template: `node_default.html5`

```html
<!-- indexer::stop -->
<dialog id="easy-popup-<?= $this->id ?>" class="easy-popup-container <?= $this->class ?>">
    <div class="easy-popup-inside">
        <form method="dialog">
            <button class="easy-popup-close">X</button>
        </form>

        <div class="easy-popup-content">
        	<?= $this->buffer ?>
        </div>
    </div>
</dialog>
<!-- indexer::continue -->

<script>
    const popup = document.getElementById('easy-popup-<?= $this->id ?>');
    
    popup.showModal();
    document.documentElement.classList.add('easy-popup-open');
    
    popup.addEventListener('close', () => {
        document.documentElement.classList.remove('easy-popup-open');
    });
</script>
```

**Comment by m-werk** [comment]
Spitze, danke, das funktioniert prima. Was noch (wenn ich so frei sein darf) auf die todo kommen sollte, ist so eine Art "Öffnungstyp" wie "Zeit, Button(das würde schon bestehen), Scrollposition, und noch Felder wie "Start, Stop...)
